---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ingress
  name: ingress
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: ingress
  type: NodePort
