---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: ingress
  name: ingress
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: ingress
      name: ingress
    spec:
      containers:
        - name: envoy
          image: lyft/envoy:a733fc5932b34c984712c3090ba74fe54b480324
          command: 
            - "/usr/local/bin/envoy"
          args:
            - "--config-path /etc/envoy/envoy.json"
            - "--mode serve"
            - "--service-cluster ingress"
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/envoy
      volumes:
        - name: config
          configMap:
            name: ingress
