---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user
  name: user
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: user
  type: ClusterIP
  clusterIP: None

