---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: zipkin
  name: zipkin
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: zipkin
      name: zipkin
    spec:
      containers:
        - name: zipkin
          image: docker.io/openzipkin/zipkin:latest
          ports:
            - containerPort: 9411
              protocol: TCP
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace