---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        prometheus.io/scrape: "true"
      name: frontend
    spec:
      containers:
        - name: frontend
          image: quay.io/bakins/kubernetes-envoy-example:latest
          imagePullPolicy: IfNotPresent
          command: 
            - "/usr/bin/frontend"
            - "--address=127.0.0.1:9090"
            - "--endpoint=127.0.0.1:7070"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6060
          readinessProbe:
            httpGet:
              path: /healthz
              port: 6060
          ports:
            - containerPort: 6060
              protocol: TCP
              name: app
        - name: envoy
          image: envoyproxy/envoy-alpine:v1.5.0
          command: 
            - "/usr/local/bin/envoy"
          args:
            - "--config-path /etc/envoy/envoy.json"
            - "--mode serve"
            - "--service-cluster frontend"
          ports:
            - containerPort: 8080
              protocol: TCP
              name: app
          volumeMounts:
            - name: envoy
              mountPath: /etc/envoy
            - name: certs
              mountPath: /certs
          livenessProbe:
            httpGet:
              path: /server_info
              port: 8001
          readinessProbe:
            httpGet:
              path: /server_info
              port: 8001
        - name: statsd
          image: prom/statsd-exporter:master
          command: 
            - "/bin/statsd_exporter"
          args:
            - "-statsd.mapping-config=/etc/statsd/statsd.yaml"
          ports:
            - containerPort: 9102
              protocol: TCP
              name: metrics
          volumeMounts:
            - name: statsd
              mountPath: /etc/statsd
      volumes:
        - name: envoy
          configMap:
            name: frontend
        - name: statsd
          configMap:
            name: envoy-statsd
        - name: certs
          secret:
            secretName: frontend
