apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - env:
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_DASHBOARDS_JSON_ENABLED
          value: "true"
        - name: GF_DASHBOARDS_JSON_PATH
          value: /dashboards
        - name: GF_LOG_MODE
          value: console
        image: grafana/grafana:4.4.3
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
#        volumeMounts:
#        - mountPath: /dashboards
#          name: grafana
#      volumes:
#      - configMap:
#          defaultMode: 420
#          name: grafana
#        name: grafana
