apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - env:
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_LOG_MODE
          value: console
        image: grafana/grafana:4.4.3
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
      - name: dashboard-updater
        image: quay.io/bakins/kubernetes-envoy-example:latest
        command:
        - kubernetes-grafana-updater
        - dashboards
      - name: datasource-updater
        image: quay.io/bakins/kubernetes-envoy-example:latest
        command:
        - kubernetes-grafana-updater
        - datasources
      

