---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: ingress
  name: ingress
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: ingress
      annotations:
        prometheus.io/scrape: "true"
      name: ingress
    spec:
      containers:
        - name: envoy
          image: envoyproxy/envoy-alpine:v1.5.0
          command: 
            - "/usr/local/bin/envoy"
          args:
            - "--config-path /etc/envoy/envoy.json"
            - "--mode serve"
            - "--v2-config-only"
            - "--service-cluster ingress"
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/envoy
            - name: certs
              mountPath: /certs
          livenessProbe:
            httpGet:
              path: /server_info
              port: 8001
          readinessProbe:
            httpGet:
              path: /server_info
              port: 8001
        - name: statsd
          image: prom/statsd-exporter:master
          command: 
            - "/bin/statsd_exporter"
          args:
            - "-statsd.mapping-config=/etc/statsd/statsd.yaml"
          ports:
            - containerPort: 9102
              protocol: TCP
              name: metrics
          volumeMounts:
            - name: statsd
              mountPath: /etc/statsd
      volumes:
        - name: config
          configMap:
            name: ingress
        - name: statsd
          configMap:
            name: envoy-statsd
        - name: certs
          secret:
            secretName: ingress
