---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: item
  name: item
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: item
      annotations:
        prometheus.io/scrape: "true"
      name: item
    spec:
      containers:
        - name: proxy
          image: quay.io/bakins/kubernetes-envoy-example-php:latest
          imagePullPolicy: IfNotPresent
          command: 
            - /usr/bin/grpc-fastcgi-proxy
            - "--address=127.0.0.1:9090"
            - "--fastcgi=tcp://127.0.0.1:9000"
            - "--aux-address=127.0.0.1:5050"
            - "--aux-path=/healthz.php=/app/healthz.php"
            - "--aux-path=/status"
            - "--aux-path=/ping"
            - "/app/index.php"
          livenessProbe:
            httpGet:
              path: /healthz.php
              port: 6060
        - name: php
          image: quay.io/bakins/kubernetes-envoy-example-php:latest
          imagePullPolicy: IfNotPresent
          command: 
            - /usr/sbin/php-fpm7
            - "--fpm-config=/config/php-fpm.conf"
            - "--nodaemonize"
            - "--force-stderr"
          volumeMounts:
            - name: php
              mountPath: /config
          ports:
            - containerPort: 6060
              protocol: TCP
              name: metrics
          livenessProbe:
            httpGet:
              path: /healthz.php
              port: 6060
        - name: exporter
          image: quay.io/bakins/kubernetes-envoy-example-php:latest
          imagePullPolicy: IfNotPresent
          command: 
            - /usr/bin/php-fpm-exporter
            - "--addr=:8888"
            - "--endpoint=http://127.0.0.1:5050/status"
          ports:
            - containerPort: 8888
              protocol: TCP
              name: metrics
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8888
        - name: envoy
          image: envoyproxy/envoy-alpine:v1.5.0
          command: 
            - "/usr/local/bin/envoy"
          args:
            - "--config-path /etc/envoy/envoy.json"
            - "--mode serve"
            - "--service-cluster item"
          ports:
            - containerPort: 8080
              protocol: TCP
              name: app
          volumeMounts:
            - name: envoy
              mountPath: /etc/envoy
            - name: certs
              mountPath: /certs
          livenessProbe:
            httpGet:
              path: /server_info
              port: 8001
          readinessProbe:
            httpGet:
              path: /server_info
              port: 8001
        - name: statsd
          image: prom/statsd-exporter:master
          command: 
            - "/bin/statsd_exporter"
          args:
            - "-statsd.mapping-config=/etc/statsd/statsd.yaml"
          ports:
            - containerPort: 9102
              protocol: TCP
              name: metrics
          volumeMounts:
            - name: statsd
              mountPath: /etc/statsd
      volumes:
        - name: envoy
          configMap:
            name: item
        - name: php
          configMap:
            name: php
        - name: statsd
          configMap:
            name: envoy-statsd
        - name: certs
          secret:
            secretName: item
