---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: order
  name: order
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: order
  type: ClusterIP
  clusterIP: None

